---
config:
    layout: elk
---
flowchart LR
    Client["Client"]
    Waiter["Waiter"]
    Admin["Admin"]
    Chef["Chef"]
    %% Актори
    User["Зареєстрований користувач"]
    Client["Клієнт"]
    Waiter["Офіціант"]
    Chef["Кухар"]
    Admin["Адміністратор"]
    NotifyService["Notification Service"]
    NotifyService["Notification Service (Push / SMS)"]

    %% Узагальнення акторів
    Client --> User
    Waiter --> User
    Chef --> User
    Admin --> User

    subgraph System ["Комунікація між залом та кухнею"]
      UC4_1(["Передати замовлення на кухню"])
      UC4_2(["Переглядати чергу замовлень на дисплеї"])
      UC4_3(["Отримувати зміни до активних замовлень"])
      UC4_4(["Керувати стоп-листом страв"])
      UC4_5(["Змінити статус страви на 'Готово'"])
      UC4_6(["Надіслати сповіщення про готовність"])
      UC4_7(["Перегляд статистики"])
    end

    Chef --> UC4_1
    %% Зв'язки акторів з прецедентами
    Client --> UC4_1
    Waiter --> UC4_1

    Chef --> UC4_2
    Chef --> UC4_3
    Chef --> UC4_4
    Chef --> UC4_5
    Chef --> UC4_7

    Client --> UC4_4
    Admin --> UC4_7

    Waiter --> UC4_4
    %% Include зв'язки
    UC4_1 -.->|"<<include>>"| UC4_2
    UC4_5 -.->|"<<include>>"| UC4_6

    Admin --> UC4_5

    UC4_4 --> NotifyService
    %% Взаємодія з сервісом сповіщень
    UC4_6 --> NotifyService
    NotifyService --> Waiter