---
config:
    layout: elk
---
flowchart LR
    %% Актори
    User["Зареєстрований користувач"]
    Client["Клієнт"]
    Waiter["Офіціант"]
    Guest["Гість"]

    %% Узагальнення акторів
    Client --> User
    Waiter --> User

    subgraph System ["Оформлення та редагування замовлень"]
      UC2_1(["Сформувати замовлення в залі"])
      UC2_2(["Переглянути проміжну вартість чека"])
      UC2_3(["Редагувати склад замовлення"])
      UC2_4(["Pre-order"])
      UC2_5(["Оформлення замовлення 'із собою'"])
      UC2_6(["Підтвердити замовлення"])
      UC2_7(["Згенерувати цифровий код видачі"])
    end

    %% Зв'язки акторів з прецедентами
    Client --> UC2_1
    Client --> UC2_2
    Client --> UC2_3
    Client --> UC2_4
    Client --> UC2_6

    Waiter --> UC2_1
    Waiter --> UC2_3
    Waiter --> UC2_6
    
    Guest --> UC2_1

    Guest --> UC2_5

    %% Include зв'язки
    UC2_1 -.->|"<<include>>"| UC2_2
    UC2_1 -.->|"<<include>>"| UC2_6

    UC2_5 -.->|"<<include>>"| UC2_2
    UC2_5 -.->|"<<include>>"| UC2_6
    UC2_5 -.->|"<<include>>"| UC2_7

    %% Extend зв'язки
    UC2_4 -.->|"<<extend>>"| UC2_1
    UC2_3 -.->|"<<extend>> (до початку готування)"| UC2_1