---
config:
    layout: elk
---
flowchart LR
    %% Актори
    User["Зареєстрований користувач"]
    Client["Клієнт"]
    Waiter["Офіціант"]
    Guest["Гість"]

    %% Узагальнення акторів
    Client --> User
    Waiter --> User

    subgraph System ["Оформлення та редагування замовлень"]
      UC1(["Сформувати замовлення в залі"])
      UC2(["Переглянути проміжну вартість чека"])
      UC3(["Редагувати склад замовлення"])
      UC4(["Pre-order"])
      UC5(["Оформлення замовлення 'із собою'"])
      UC4(["Оформити попереднє замовлення (Pre-order)"])
      UC5(["Оформити замовлення 'із собою' (Takeaway)"])
      UC6(["Підтвердити замовлення"])
      UC7(["Згенерувати цифровий код видачі"])
    end

    %% Зв'язки акторів з прецедентами
    Client --> UC1
    Client --> UC2
    Client --> UC3
    Client --> UC4
    Client --> UC6

    Waiter --> UC1
    Waiter --> UC3
    Waiter --> UC6
    
    Guest --> UC1

    Guest --> UC5

    %% Include зв'язки
    UC1 -.->|"<<include>>"| UC2
    UC1 -.->|"<<include>>"| UC6

    UC5 -.->|"<<include>>"| UC2
    UC5 -.->|"<<include>>"| UC6
    UC5 -.->|"<<include>>"| UC7

    %% Extend зв'язки
    UC4 -.->|"<<extend>>"| UC1
    UC3 -.->|"<<extend>> (до початку готування)"| UC1